[package]
name = "rust-blog"
version = "0.1.0"
edition = "2021"

[package.metadata.leptos]
style-file = "style/output.css"

[dependencies]
leptos = { version = "0.6.13", features = ["csr"] }
leptos_router = { version = "0.6.13", features = ["csr"] }
